spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 3772
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: create
          open-in-view: false
